### ISSUE TITLE
change slashes after cdnify

### ISSUE THREAD

**Issue by yabasha** [kaiqigong/gulp-cdnify#12]
Hi,

I set my sources path to:
`<link rel="stylesheet" href="css/main.css">`
`<script src="js/bundle.js"></script>`

after running cdnify:

```
gulp.src(config.source.index)
    .pipe($.cdnify({
      base: 'http://my.cdn.path-cdn.com/'
    }))
    .pipe(gulp.dest(config.dist.root));
```

The output:

```
<link rel="stylesheet" href="http://my.cdn.path-cdn.com\css\main.css">
<script src="http://my.cdn.path-cdn.com\js\bundle.js"></script>
```

**Comment by kaiqigong** [comment]
Is there any tasks after this? which might change the result. I have updated the sample.
https://github.com/kaiqigong/gulp-cdnify/commit/3be1d78c960ee2ba85041fe6977e4a1ca3cc725f

**Comment by harikrishkk** [comment]
@kaiqigong  I am having the exact same problem :(  Here is a task that i had written to take the HTML file, inject the styles and scripts using gulp-inject, check for errors with plumber, and since i need to optionally switch between dev and prod builds, i set a flag with gylp-if and yargs, and if its a production build, i need to change the local URLs to the CDN based ones.

The problem is that, the urls coming as output when passed via cdnify is:

``` javascript
<link rel="stylesheet" href="http://some-cdn\css\bootstrap.min.css">
    <link rel="stylesheet" href="http://some-cdn\css\my-styles.css">
```

**Gulpfile.js**

``` javascript
gulp.task('index',['copy-files'], function () {
    var sources = gulp.src(config.allFiles, {read: false});    
    return gulp
        .src(config.index) 
        .pipe(inject(sources)) 
        .pipe(plumber())
        .pipe(gulpif(args.verbose,cdnify({base: 'http://some-cdn/cdn/'})))
        .pipe(plumber())
        .pipe(gulp.dest(config.dest));
});

gulp.task('copy-files',['trash'], function(){
    return gulp
        .src(config.assets,{ "base" : "." })
        .pipe(gulp.dest(config.dest));     
});

gulp.task('trash', function(){
    return del([
        'dist/css/',
        'dist/js/',
        'dist/img/',
        'dist/index.html'        
    ]);    
});
```

Any pointers would be of great help!!..

**Comment by kaiqigong** [comment]
@harikrishkk is there an executable sample project? OS, node version?

**Comment by levinhtin** [comment]
i having same issue on windows, node 4.4.2

**Comment by kaiqigong** [comment]
Can you give an sample code? I have no idea how this happen

发自我的 iPhone

**Comment by beefo** [comment]
+1
I have a project where this is happening. If it helps you can clone the repo and "gulp build" to test it out. https://github.com/Geotab/addin-fuel-transaction-import/tree/v2.0

**Comment by kaiqigong** [comment]
Please use gulp-cdnizer instead.

**Comment by kaiqigong** [comment]
@raygesualdo thx, have published already. 1.0.7
