### ISSUE TITLE
CDNify <picture> element

### ISSUE THREAD

**Issue by tigranpetrossian** [kaiqigong/gulp-cdnify#16]
~~The module currently doesn’t affect URLs in `<picture>` element. Would be great if that was added to the functionality.~~

Edit: Doesn't affect the `srcset` attribute within `<picture>` element.

**Comment by kaiqigong** [comment]
Hi @tigranpetrossian, it can be supported by some config below.
```html
<picture>
  <source srcset="/some/path/smaller.jpg" media="(max-width: 768px)">
  <source srcset="/some/path/default.jpg">
</picture>
```

```javascript
.pipe(cdnify({
    base: 'http://my.cdn.path-cdn.com/',
    html: {
      'source[srcset]': 'srcset'
    }
  }))
```
