### ISSUE TITLE
cdnify a background-url in a ng-style 

### ISSUE THREAD

**Issue by Simobain** [kaiqigong/gulp-cdnify#17]
Hi, 

I have a, as showed below a ng-style attribute that changes dynamically a background-img.  
![image](https://cloud.githubusercontent.com/assets/4479510/24006039/eaece760-0a6a-11e7-8c69-cae13ea9685b.png)

Gulp-cdnify does not recognize it. What can I do ? 

Thanks

**Comment by kaiqigong** [comment]
Hi @Simobain , try it in angular way. like,
in template
```
ng-style="{'background-image': 'url(' + vm.cdnPath +'/' + destination.urlPictureCity+ ')'}"
```
in js
```
vm.cdnPath = someEnvVar === 'production' ? 'http://your/cdn/path' : '';
```

**Comment by Simobain** [comment]
Thanks ! It should work. I made it by changing the css tag background-url by an img src.
