### ISSUE TITLE
gulp-cdnify add a cdn to external link.

### ISSUE THREAD

**Issue by Simobain** [kaiqigong/gulp-cdnify#18]
![image](https://cloud.githubusercontent.com/assets/4479510/24292206/9dd29772-108c-11e7-9f7b-6d79f5cbb950.png)
this text is then digested by ng-bind-html. 

and the result is 
![image](https://cloud.githubusercontent.com/assets/4479510/24292245/ca056dce-108c-11e7-835c-c5d273fad042.png)

**Comment by kaiqigong** [comment]
Hi @Simobain try to use ng-src instead.
The `gulp-cdnify` will change all the img[src] tags by default.
