### ISSUE TITLE
Support for srcset attributes?

### ISSUE THREAD

**Issue by tigranpetrossian** [kaiqigong/gulp-cdnify#3]
It would be great if the plugin dealt with srcset as well, e.g. `<img src="small.jpg" srcset="medium.jpg 1000w, large.jpg 2000w">` or `<img src="picture.jpg" srcset="picture-2x.jpg 2x">`. Any chance to make it happen? :-)

**Comment by kaiqigong** [comment]
Hmm, good suggestion, this a feature worth of supporting.
Let me try :smile:

**Comment by kaiqigong** [comment]
@tigranpetrossian have a try
