### ISSUE TITLE
Cdnify relative references

### ISSUE THREAD

**Issue by tigranpetrossian** [kaiqigong/gulp-cdnify#4]
Is there a way to make the plugin work with just relative (not root-relative) links? E.g. `src="images/picture.jpg"` instead of `src="/foo/bar/images/picture.jpg"` when referenced from `/foo/bar/index.html`.

**Comment by kaiqigong** [comment]
@tigranpetrossian 
Hi, thanks for your feedback!
Here's the solution:

```
.pipe(cdnify({
    base: 'http://pathto/your/cdn/',
    rewriter: function(url, process) {
      if (/^\//.test(url)) {
        // root path, return as it is
        return url;
      } else {
        return process(url);
      }
    }
  }))
```

Need to add a rewrite method to do this.

**Comment by tigranpetrossian** [comment]
@kaiqigong Thanks! I'm not sure if I'm getting this right but doesn't seem to work as is. Could you clarify just a little bit on what `process`does?

**Comment by kaiqigong** [comment]
@tigranpetrossian `process` is the default method to process the url to cdn path. I have updated the [samples](https://github.com/kaiqigong/gulp-cdnify/tree/master/sample).

**Comment by tigranpetrossian** [comment]
@kaiqigong I'm sorry, I poorly composed my first question hence all the misunderstanding. What I was asking is if it's possible to turn `src="images/picture.jpg"` (which is located at `/foo/bar/images/picture.jpg`) into `src="http://cdn.example.com/foo/bar/images/picture.jpg`
